### ISSUE TITLE
项目跑起来之后需要更新，更新之后程序就崩溃啦

### ISSUE THREAD

**Issue by ibwei** [YanYuanFE/RN-GitHub#6]
![image](https://user-images.githubusercontent.com/25237993/64664568-21d5af80-d482-11e9-90dc-dc7ef27a3ce8.png)

如图，更新之后，就打不开项目了。

**Comment by YanYuanFE** [comment]
你把热更新的地方的代码注释下

**Comment by YanYuanFE** [comment]
ImmediateCheckCodePush(),这个方法
